export const VIETNAMESE_BANKS = [
  { id: "icb", name: "VietinBank" },
  { id: "vcb", name: "Vietcombank" },
  { id: "bidv", name: "BIDV" },
  { id: "vba", name: "Agribank" },
  { id: "tcb", name: "Techcombank" },
  { id: "mbb", name: "MBBank" },
  { id: "acb", name: "ACB" },
  { id: "vpbank", name: "VPBank" },
  { id: "tpbank", name: "TPBank" },
  { id: "sacombank", name: "Sacombank" },
  { id: "shb", name: "SHB" },
  { id: "vib", name: "VIB" },
  { id: "ocb", name: "OCB" },
  { id: "msb", name: "MSB" },
  { id: "hdb", name: "HDBank" },
  { id: "scb", name: "SCB" },
  { id: "seabank", name: "SeABank" },
  { id: "lienvietpostbank", name: "LPBank" },
  { id: "pvcombank", name: "PVcomBank" },
  { id: "bacabank", name: "Bac A Bank" },
  { id: "namabank", name: "Nam A Bank" },
  { id: "abbank", name: "ABBANK" },
  { id: "vietabank", name: "VietABank" },
];
