export const tokens = {
  colors: {
    bg: 'rgb(var(--color-bg))',
    bgCard: 'rgb(var(--color-bg-card))',
    bgWarm: 'rgb(var(--color-bg-warm))',
    bgHover: 'rgb(var(--color-bg-hover))',
    border: 'rgb(var(--color-border))',
    borderLight: 'rgb(var(--color-border-light))',
    textPrimary: 'rgb(var(--color-text-primary))',
    textSecondary: 'rgb(var(--color-text-secondary))',
    textMuted: 'rgb(var(--color-text-muted))',
    accent: 'rgb(var(--color-accent))',
    accentDark: 'rgb(var(--color-accent-dark))',
    accentSoft: 'rgb(var(--color-accent-soft))',
    gold: 'rgb(var(--color-gold))',
    goldLight: 'rgb(var(--color-gold-light))',
  },
  spacing: {
    xs: '0.25rem',
    sm: '0.5rem',
    md: '1rem',
    lg: '1.5rem',
    xl: '2rem',
    '2xl': '3rem',
    '3xl': '4rem',
  },
  radius: {
    sm: '0.375rem',
    md: '0.5rem',
    lg: '0.75rem',
    xl: '1rem',
    '2xl': '1.5rem',
    full: '9999px',
  },
  shadow: {
    sm: '0 1px 2px rgba(0,0,0,0.05)',
    md: '0 4px 6px -1px rgba(0,0,0,0.1)',
    lg: '0 10px 15px -3px rgba(0,0,0,0.1)',
    xl: '0 20px 25px -5px rgba(0,0,0,0.1)',
  },
  fontSize: {
    xs: ['0.75rem', { lineHeight: '1rem' }],
    sm: ['0.875rem', { lineHeight: '1.25rem' }],
    base: ['1rem', { lineHeight: '1.5rem' }],
    lg: ['1.125rem', { lineHeight: '1.75rem' }],
    xl: ['1.25rem', { lineHeight: '1.75rem' }],
    '2xl': ['1.5rem', { lineHeight: '2rem' }],
    '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
  },
} as const;
